In [1]:
import numpy as np
    
np.random.seed(80)
array = np.random.randint(1, 101, (4, 4))
print(array)
print(array[array > 50])
print(np.sum(array, axis=0))
print(np.sum(array, axis=1))
print(np.max(array, axis=0))
print(np.max(array, axis=1))
print(np.min(array, axis=0))
print(np.min(array, axis=1))
print(np.mean(array, axis=0))
print(np.mean(array, axis=1))     

[[48 61 39 84]
 [11 51  4 87]
 [24 16 82  6]
 [65 10 93 43]]
[61 84 51 87 82 65 93]
[148 138 218 220]
[232 153 128 211]
[65 61 93 87]
[84 87 82 93]
[11 10  4  6]
[39  4  6 10]
[37.  34.5 54.5 55. ]
[58.   38.25 32.   52.75]


In [3]:
import numpy as np
from IPython.display import display
import pandas as pd

new_games = {
"Final Fantasy VII Rebirth": 69.99,
"Astro Bot": 59.99,
"Star Wars Outlaws": 69.99,
"Silent Hill 2 Remake": 69.99,
"Elden Ring: Shadow of the Erdtree": 39.99,
"Dragon Age: The Veilguard": 69.99,
"Metaphor: ReFantazio": 59.99
}
games_series = pd.Series(new_games)
    
print("price:", games_series["Metaphor: ReFantazio"])
print(games_series.index)
print("index price[3]:" , games_series.iloc[3])
print("sum all games:", games_series.values.sum())

price: 59.99
Index(['Final Fantasy VII Rebirth', 'Astro Bot', 'Star Wars Outlaws',
       'Silent Hill 2 Remake', 'Elden Ring: Shadow of the Erdtree',
       'Dragon Age: The Veilguard', 'Metaphor: ReFantazio'],
      dtype='object')
index price[3]: 69.99
sum all games: 439.93
